title = "Centipede"

[Mongo]
Host = "10.1.72.26"
Post = "27017"
Database = "douban"

[HttpClient]
#ProxyDisable = false
#ProxyHost = "proxy.abuyun.com"
#ProxyPort = "9020"
#ProxyUser = "HR03Y5983TE1C0MD"
#ProxyPassword = "72DAB06BEF59368F"
ProxyDisable = false
ProxyHost = "127.0.0.1"
ProxyPort = "8878"
ProxyUser = ""
ProxyPassword = ""

[Redis]
Host = "10.1.72.26:6379"
Db = 0